### ISSUE TITLE
Flow control keywords and enum variants have the same color

### ISSUE THREAD

**Issue by crumblingstatue** [Nercury/atom-rusty-dark-syntax#1] opened 2016-02-21 19:01 UTC
It's a bit confusing, as they are distinct things.

![](http://i.imgur.com/3v4ZUye.png)

**Comment by Nercury** [comment] 2016-02-21 19:11
Yes, that was conscious decision - but that only happens for `Some`, `None`, `Result`, `Err`. `rust-language` was marking these differently than other enums, so I made them the same color as control-flow keywords, because usually they are part of the control flow.

There is no special marking for other rust types and enums, so the only other choice is to leave these keywords the same color as plain text.

**Comment by Nercury** [comment] 2016-02-25 21:27
Closing because it was by design.

**Closed as completed by Nercury** 2016-02-25 21:27 UTC
